name 'driebit-xhgui'
version '0.2.0'
description 'Installs and configures XHGui, a MongoDB-backed GUI for XHProf.'
dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
dependency 'tPl0ch/composer', '>= 1.2.0'
dependency 'puppetlabs/mongodb', '>= 0.8.0'
